package(default_visibility = ["//visibility:public"])

filegroup(
    name = "static",
    srcs = glob([
        "**/*.html",
        "**/*.txt",
        "**/*.xml",
        "**/*.js",
        "**/*.jpg",
        "**/*.jpeg",
        "**/*.png",
        "**/*.svg",
        "**/*.ico",
        "**/*.webmanifest",
        "**/*.json",
    ]),
)
