# Configuration for deployment to kubernetes

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{NAME}}
spec:
  selector:
    matchLabels:
      app: {{NAME}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{NAME}}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: {{NAME}}
          image: gcr.io/flame-build/{{NAME}}:server_image
          imagePullPolicy: Always
          env:
          - name: ENV
            value: "production"
          - name: SERVICE_NAME
            value: "app-backend"
          - name: VERSION
            value: "prod-1.0"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: {{NAME}}
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{NAME}}-ingress
  annotations:
    networking.gke.io/managed-certificates: ""
spec:
  backend:
    serviceName: frontend
    servicePort: 80
